export const sections = [
  {
    title: "Introduction",
    contents: (
      <span>
        Welcome to bonfire's Privacy Policy. We want to keep your privacy
        "safe". <br />
      </span>
    ),
  },
  {
    title: "Contact Information",
    contents: (
      <>
        <ul>
          <li>
            <b>Owner and Data Controller: </b>bonfire-io <br />
          </li>
          <li>
            <b>Email:</b> peopleundercloud@gmail.com <br />
          </li>
          <li>
            <b>Github Project:</b>
            <a
              href="https://github.com/bonfire-io/bonfire"
              target="_blank"
              rel="noreferrer"
            >
              https://github.com/bonfire-io/bonfire
            </a>
          </li>
        </ul>
      </>
    ),
  },
  {
    title: "Definitions",
    contents: (
      <>
        <ul>
          <li>
            <b>Service</b>
            <br />
            Service means the bonfire chrome extension operated by Bonfire-io.
          </li>
          <li>
            <b>Personal Data</b>
            <br />
            Personal Data means data about a living individual who can be
            identified from those data (or from those and other information
            either in our possession or likely to come into our possession).
          </li>
          <li>
            <b>Usage Data</b>
            <br />
            Usage Data is data collected automatically either generated by the
            use of the Service or from the Service infrastructure itself (for
            example, the duration of a page visit).
          </li>
          <li>
            <b>Cookies</b>
            <br />
            Cookies are Trackers consisting of small sets of data stored in the
            User's browser.
          </li>
          <li>
            <b>Data Controller</b>
            <br />
            Data Controller means the natural or legal person who (either alone
            or jointly or in common with other persons) determines the purposes
            for which and the manner in which any personal information are, or
            are to be, processed. For the purpose of this Privacy Policy, we are
            a Data Controller of your Personal Data.
          </li>
        </ul>
      </>
    ),
  },
  {
    title: "Types of Data collected",
    contents: (
      <span>
        Our system does not collect any critical personal data. (like email,
        name, location, birth, etc) <br />
        So, Login & Sign up do not require this informations. <br />
        <ol>
          <li>
            We just collect your nickname, hashed password, and profile image in
            sign up step.
          </li>
          <li>
            And we collect your messages sent by you and others. Our service's
            goal is providing message system. So, we collect and show that
            everyone.
          </li>
          <li>
            And, we collect your log information from google analytics and
            advertising. This information is described bellow.
          </li>
          <li>
            We also use "cookies" (and Chrome Extension Storage Sync) and other
            Internet technologies to collect information and improve our
            Services.
          </li>
        </ol>
        If you find defacts on our privacy system, welcome to contact the Owner.
      </span>
    ),
  },
  {
    title: "Who we share your personal information",
    contents: (
      <>
        <span>
          We share your personal information with bellow third parties.
          <ul>
            <li>
              <b>Other users: </b>
              They can see your profile information and any other information
              you choose to share with them through the Services.
            </li>
            <li>
              <b>Cloud Service Providers: </b>
              We use cloud service for data storage, include Azure, GCP, AWS.
            </li>
            <li>
              <b>Analytics Providers: </b>
              Google Analytics is a web analysis service provided by Google LLC
              or by Google Ireland Limited, depending on the location Meow
              Playground is accessed from, (“Google”). Google utilizes the Data
              collected to track and examine the use of Meow Playground, to
              prepare reports on its activities and share them with other Google
              services. Google may use the Data collected to contextualize and
              personalize the ads of its own advertising network. Personal Data
              processed: Cookies; Usage Data. <br />
              Place of processing: United States –&nbsp;
              <a
                href="https://policies.google.com/privacy"
                target="_blank"
                rel="noopener noreferrer"
              >
                Privacy Policy
              </a>
              &nbsp;–&nbsp;
              <a
                href="https://tools.google.com/dlpage/gaoptout?hl=en"
                target="_blank"
                rel="noopener noreferrer"
              >
                Opt Out
              </a>
              ; Ireland –&nbsp;
              <a
                href="https://policies.google.com/privacy"
                target="_blank"
                rel="noopener noreferrer"
              >
                Privacy Policy
              </a>
              &nbsp;–&nbsp;
              <a
                href="https://tools.google.com/dlpage/gaoptout?hl=en"
                target="_blank"
                rel="noopener noreferrer"
              >
                Opt Out
              </a>
              .
            </li>
            <li>
              <b>Google AdSense: </b>
              Google AdSense is an advertising service provided by Google
              Ireland Limited. This service uses the “DoubleClick” Cookie, which
              tracks use of Meow Playground and User behavior concerning ads,
              products and services offered. Users may decide to disable all the
              DoubleClick Cookies by going to: Google Ad Settings. Personal Data
              processed: Cookies; Usage Data. Place of processing: Ireland –
              <a
                href="https://policies.google.com/privacy"
                target="_blank"
                rel="noopener noreferrer"
              >
                Privacy Policy
              </a>
              &nbsp;–&nbsp;
              <a href="https://adssettings.google.com/authenticated#display_optout">
                Opt Out
              </a>
            </li>
          </ul>
        </span>
      </>
    ),
  },
];
