export const sections = [
  {
    title: "Introduction",
    contents: (
      <span>
        Welcome to Crypto Creatures' Privacy Policy. We want to keep your
        privacy "safe". <br />
      </span>
    ),
  },
  {
    title: "Contact Information",
    contents: (
      <>
        <ul>
          <li>
            <b>Owner and Data Controller: </b>Crypto Creatures-io <br />
          </li>
          <li>
            <b>Email:</b> trung0905042@gmail.com <br />
          </li>
        </ul>
      </>
    ),
  },
  {
    title: "Definitions",
    contents: (
      <>
        <ul>
          <li>
            <b>Service</b>
            <br />
            Service means Crypto Creatures, a GameFi application operated by
            Crypto Creatures-io.
          </li>
          <li>
            <b>Personal Data</b>
            <br />
            Personal Data means data about a living individual who can be
            identified from those data (or from those and other information
            either in our possession or likely to come into our possession).
          </li>
          <li>
            <b>Usage Data</b>
            <br />
            Usage Data is data collected automatically either generated by the
            use of the Service or from the Service infrastructure itself (for
            example, the duration of a page visit).
          </li>
          <li>
            <b>Cookies</b>
            <br />
            Cookies are Trackers consisting of small sets of data stored in the
            User's browser.
          </li>
          <li>
            <b>Data Controller</b>
            <br />
            Data Controller means the natural or legal person who (either alone
            or jointly or in common with other persons) determines the purposes
            for which and the manner in which any personal information are, or
            are to be, processed. For the purpose of this Privacy Policy, we are
            a Data Controller of your Personal Data.
          </li>
        </ul>
      </>
    ),
  },
  {
    title: "Types of Data Collected",
    contents: (
      <span>
        Our system does not collect any critical personal data (like email,
        name, location, birthdate, etc.). <br />
        Therefore, login and sign-up do not require such information. <br />
        <ol>
          <li>
            We only collect your nickname, hashed password, and profile image
            during the sign-up process.
          </li>
          <li>
            We collect messages sent by you and others as part of the Service's
            messaging system.
          </li>
          <li>
            We collect log information through Google Analytics and advertising
            services. This information is described below.
          </li>
          <li>
            We also use "cookies" (and Chrome Extension Storage Sync) and other
            Internet technologies to collect information and improve our
            Services.
          </li>
        </ol>
        If you discover any defects in our privacy system, please contact the
        Owner.
      </span>
    ),
  },
  {
    title: "Who We Share Your Personal Information With",
    contents: (
      <>
        <span>
          We share your personal information with the following third parties:
          <ul>
            <li>
              <b>Other Users: </b>
              They can see your profile information and any other information
              you choose to share with them through the Services.
            </li>
            <li>
              <b>Cloud Service Providers: </b>
              We use cloud services for data storage, including Azure, GCP, and
              AWS.
            </li>
            <li>
              <b>Analytics Providers: </b>
              We use Google Analytics to track and examine the use of Crypto
              Creatures, prepare reports on its activities, and share them with
              other Google services. Google may use the Data collected to
              contextualize and personalize ads. Personal Data processed
              includes Cookies and Usage Data. <br />
              Place of processing:&nbsp;
              <a
                href="https://policies.google.com/privacy"
                target="_blank"
                rel="noopener noreferrer"
              >
                Privacy Policy
              </a>
              &nbsp;–&nbsp;
              <a
                href="https://tools.google.com/dlpage/gaoptout?hl=en"
                target="_blank"
                rel="noopener noreferrer"
              >
                Opt Out
              </a>
              .
            </li>
          </ul>
        </span>
      </>
    ),
  },
  {
    title: "Your Rights",
    contents: (
      <span>
        You have the right to access, rectify, erase, and restrict the
        processing of your personal data. If you wish to exercise these rights,
        please contact us at trung0905042@gmail.com.
      </span>
    ),
  },
];
